#include <iostream>
#include <string>
#include <limits>
#include <vector>
#include <cstdint>

/*Generated by Claude Sonnet 5 using the prompt "String to int parse function without using a standard library"
Negative and underflow protection was removed as they were not necessary and could potentially cause issues
*/
bool stringToInt(const std::string& str, int& result) {
    result = 0;

    if (str.empty()) {
        return false; // no digits at all
    }

    for (size_t i = 0; i < str.length(); i++) {
        char c = str[i];

        // Check if character is a digit
        if (c < '0' || c > '9') {
            return false; // invalid character found
        }

        int digit = c - '0';

        // Overflow check before multiplying/adding
        if (result > (std::numeric_limits<int>::max() - digit) / 10) {
            return false; // would overflow
        }

        result = result * 10 + digit;
    }

    return true;
}

bool validateOctet(const std::string& octet) {
    int i;
    if (octet.empty()) {
        return false;
    }
    if (octet[0] == '0' and octet.size() > 1) { // reject leading 0s
        return false;
    }
    if (octet.size() > 3) {
        return false;
    }
    if (!stringToInt(octet, i)) {
        return false;
    }
    if (i > 255) {
        return false;
    }
    return true;
}

bool validatePort(const std::string& port) {
    int i;
    if (port.empty()) {
        return false;
    }
    if (port[0] == '0' and port.size() > 1) { // reject leading 0s
        return false;
    }
    if (port.size() > 5) {
        return false;
    }
    if (!stringToInt(port, i)) {
        return false;
    }
    if (i > 65535) {
        return false;
    }
    return true;
}

/*Generated by Claude Sonnet 5 using the prompt "Join string vector with delimiter function"*/
std::string joinWithDelimiter(const std::vector<std::string>& parts, char delimiter) {
    std::string result;

    for (size_t i = 0; i < parts.size(); i++) {
        result += parts[i];

        // Add delimiter after every element except the last
        if (i != parts.size() - 1) {
            result += delimiter;
        }
    }

    return result;
}

/*Generated by Claude Sonnet 5 using the prompt "function to convert a 4 octet ipv4 vector to a single decimal"
Modified to take in a string vector instead of an int vector
*/
bool octetsToDecimal(const std::vector<std::string>& octets, unsigned long& result) {
    if (octets.size() != 4) {
        return false; // must have exactly 4 octets for IPv4
    }

    result = 0;

    for (size_t i = 0; i < octets.size(); i++) {
        int octectInt;
        stringToInt(octets[i], octectInt);
        if (octectInt > 255) {
            return false; // invalid octet value
        }

        // Shift result left by 8 bits and OR in the next octet
        result = (result << 8) | octectInt;
    }

    return true;
}

bool extractIPv4(const std::string& str, unsigned long& outAddress, std::string& outPort, std::string& parsedIp) {
    std::string octet;
    std::vector<std::string> octetVector;
    std::string port;
    bool acceptOctet = true; // controls new ip characters should be accepted
    bool acceptPort = false;
    for (size_t i = 0; i < str.length(); i++) {
        if (std::isdigit(static_cast<unsigned char>(str[i])) and acceptOctet) {
            octet += str[i];
        } else if (str[i] == '.' and acceptOctet) {
            if (validateOctet(octet)) {
                octetVector.push_back(octet);
                octet.clear();
            } else {
                octet.clear();
                octetVector.clear();
                acceptOctet = false;
            }
        } else if (str[i] == ':') {
            if (acceptPort) {
                octet.clear();
                octetVector.clear();
                acceptOctet = false;
                acceptPort = false;
                continue;
            }
            if (validateOctet(octet)) {
                octetVector.push_back(octet);
                if (octetVector.size() == 4) {
                    acceptOctet = false;
                    acceptPort = true;
                    octet.clear();
                    continue;
                } 
            }
                octetVector.clear();
                octet.clear();
                acceptOctet = false;
        } else if (str[i] == '.' and acceptPort) {
                octet.clear();
                octetVector.clear();
                acceptOctet = false;
                acceptPort = false;
        } else if (std::isdigit(static_cast<unsigned char>(str[i])) and acceptPort) {
            port += str[i];
        } else if (!std::isdigit(static_cast<unsigned char>(str[i]))) {
            if (acceptPort) {
                if (validatePort(port)) {
                    parsedIp = joinWithDelimiter(octetVector, '.');
                    parsedIp += ":";
                    parsedIp += port;
                    outPort = port;
                    octetsToDecimal(octetVector, outAddress);
                    return true;
                } else {
                    octetVector.clear();
                    octet.clear();
                    acceptOctet = true;
                    acceptPort = false;
                }
            } else if (acceptOctet and octetVector.size() == 3) {
                if (validateOctet(octet)) {
                    octetVector.push_back(octet);
                    octet.clear();
                    if (octetVector.size() == 4) {
                        parsedIp = joinWithDelimiter(octetVector, '.');

                        octetsToDecimal(octetVector, outAddress);
                        outPort = "none";
                        return true;
                    }
                } else {
                    octetVector.clear();
                    octet.clear();
                    acceptOctet = true;
                    acceptPort = false;
                }
            } else if (str[i] == ':' or str[i] == '.') { // don't go into an accepting state to avoid something like 19..1.1.1.1 being valid
                acceptOctet = false;
            } else {
                octetVector.clear();
                octet.clear();
                acceptOctet = true;
                acceptPort = false;
            }
        }
        
    }
    if (validateOctet(octet)) {
        octetVector.push_back(octet);
        if (octetVector.size() == 4) {
            parsedIp = joinWithDelimiter(octetVector, '.');
            octetsToDecimal(octetVector, outAddress);
            outPort = "none";
            return true;
        }
    } else if (validatePort(port)) {
        parsedIp = joinWithDelimiter(octetVector, '.');
        parsedIp += ":";
        parsedIp += port;
        outPort = port;
        octetsToDecimal(octetVector, outAddress);
        return true;
    }
    return false;
}

int main() {
    while (true) {
        std::string input;
        unsigned long outAddress;
        std::string outPort;
        std::string parsedAddress;

        std::cout << "Enter a string (or 'END' to quit): "; 
        std::getline(std::cin, input);

        if (input == "END") {
            break;
        }

        if (extractIPv4(input, outAddress, outPort, parsedAddress)) {
            std::cout << "Extracted Ipv4 address: " << parsedAddress << " (decimal value: " << outAddress << ", port: " << outPort << ")" << std::endl;
        } else {
            std::cout << "Invalid input: no valid IPv4 address found" << std::endl;
        }
    }

    return 0;
}

